import React, { StyleSheet } from 'react-native'
import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';

export default StyleSheet.create({

    container:{
        height: hp('100%'),
        width: wp('100%'),
        flex: 1,
        // alignItems: 'center',
        // justifyContent:'center',
        // backgroundColor: 'black',
    },
    backgroundImage:{
        position:'absolute',
        width: wp('100%'),
        height: hp('100%'),
        resizeMode:'cover',
        backgroundColor:'black',
        opacity: 0.8,
        zIndex:-2,
    },
    Title:{
        textAlign: 'center',
        color: 'white',
        fontFamily: 'Audrey-Medium',
        textTransform:'uppercase',
        fontSize: 55,
        marginTop: wp('40%'),
    },
    Subtitle:{
        textAlign: 'center',
        color: 'white',
        fontFamily: 'Audrey-Normal',
        fontSize: 28,
    },
    Hello:{
        fontFamily:"Quark-Bold",
        // letterSpacing:1,
        fontSize:30,
        textAlign:'center',
        marginTop:20,
    },
    Scrollable:{
        position:'absolute',
        width: wp('100%'),
        height: hp('100%'),
        // backgroundColor:'red',
        flex:1,
    },
    horizontalScrollable:{
        // maxHeight:hp('35%'),
        // marginTop:'25%',
        // backgroundColor:'yellow',
        position:'relative',
        flex:1,
        
    },
    horizontalContainer:{
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-around',
        alignContent:'space-around',
        minHeight:hp('38%'),
    },
    panel:{
        // position:'relative',
        width: '100%',
        minHeight: hp('100%'),
        marginTop:hp('87%'),
        backgroundColor: 'white',
        overflow:'hidden',
        borderTopLeftRadius:30,
        borderTopRightRadius:30,
        // padding: 10,
        flex:1,
        // justifyContent:'space-around',
        // alignContent:'space-around',
        // alignItems:'center',
    },
    boxContainerHorizontal:{
        // height:hp('60%'),
        width:wp('100%'),
        maxHeight:'65%',
        flex: 1,
        flexDirection: 'row',
        flexWrap:'wrap',
        // backgroundColor:'yellow',
        justifyContent:'space-around',
        // alignContent:'space-around',
        // marginLeft:wp('15%'),
        marginLeft:wp('-0.75%'),
        // position:'relative',
    },
    box1:{
        position:'relative',
        width:wp('93%'),
        height:wp('44%'),
        // backgroundColor:'#B0D0D3',
        backgroundColor:'black',
        borderRadius: 40,
        marginTop:hp('5%'),
        // marginRight:'auto',
        // marginLeft:'auto',
        shadowOffset:{width: 0, height: 0},
        elevation: 10,
        shadowColor: 'black',
        shadowRadius:2,
        shadowOpacity:1,
    },
    box2:{
        position:'relative',
        width:wp('46%'),
        height:wp('44%'),
        // backgroundColor:'#C08497',
        backgroundColor:'black',
        borderRadius: 40,
        // display:'flex',
        marginTop:11,
        marginRight:'auto',
        marginLeft:'auto',
        shadowOffset:{width: 0, height: 0},
        elevation: 10,
        shadowColor: 'black',
        shadowRadius:2,
        shadowOpacity:1,
    },
    box3:{
        position:'relative',
        width:wp('46%'),
        height:wp('44%'),
        backgroundColor:'#F7AF9D',
        backgroundColor:'black',
        borderRadius: 40,
        // display:'flex',
        marginTop:11,
        marginRight:'auto',
        // marginLeft:'auto',
        shadowOffset:{width: 0, height: 0},
        elevation: 10,
        shadowColor: 'black',
        shadowRadius:2,
        shadowOpacity:1,
    },
    box4:{
        position:'relative',
        width:wp('93%'),
        height:wp('44%'),
        backgroundColor:'#F7E3AF',
        backgroundColor:'black',
        borderRadius: 40,
        marginTop:11,
        // marginRight:'auto',
        // marginLeft:'auto',
        shadowOffset:{width: 0, height: 0},
        elevation: 10,
        shadowColor: 'black',
        shadowRadius:2,
        shadowOpacity:1,
    },
    boxTitle:{
        color:'black',
        fontSize:20,
    },
    boxImage:{
        height: '100%',
        width: '100%',
        resizeMode:'cover',
        borderRadius: 35,
       position:'relative',
       opacity: 0.8,
    },
    boxText:{
        fontFamily:"Audrey-Bold",
        marginTop:13,
        fontSize: 25,
        width:'100%',
        height:'100%',
        color:'white',
        position:'absolute',
        padding: 15,
    },
    bigBoxText:{
        fontFamily:"Audrey-Bold",
        textAlign:'center',
        textAlignVertical:'center',
        marginTop:13,
        fontSize: 40,
        width:'100%',
        height:'100%',
        color:'white',
        position:'absolute',
        padding: 15,
    },
    panelTitle:{
        width:'100%',
        fontSize:35,
        fontFamily:"Audrey-Bold",
        padding:10,
        marginTop:'7%',
        marginLeft:'2%',
    },
    iconContainer:{
        // height:100,
        // width:100, 
        position:'relative',
        marginLeft:'auto',
        marginTop:'auto',
        // backgroundColor:'blue',
        padding: 20,
        opacity:0.9,
    },
    circle:{
        position:'absolute',
        marginLeft:'-8%',
        marginTop:'-8%',
        height:hp('15%'),
        width:hp('15%'),
        backgroundColor:'white',
        opacity:0.3,
        borderRadius:hp('15%')/2,
    },
    bigBox:{
        position:'relative',
        width:wp('56%'),
        height:hp('35%'),
        marginHorizontal:15,
        backgroundColor:'black',
        borderRadius: 40,
        shadowOffset:{width: 0, height: 0},
        elevation: 10,
        shadowColor: 'black',
        shadowRadius:2,
        shadowOpacity:1,
    },
    // animatedView:{
    //     position:'absolute',
    //     marginTop:0,
    //     // height:hp('90%'),

    // }

    
    
})