import React, { StyleSheet } from 'react-native'
import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';

export default StyleSheet.create({

    container:{
        height: hp('100%'),
        width: wp('100%'),
        flex: 1,
        // alignItems: 'center',
        // justifyContent:'center',
        // backgroundColor: 'black',
    },
    backgroundImage:{
        position:'absolute',
        width: wp('100%'),
        height: hp('100%'),
        resizeMode:'cover',
        backgroundColor:'black',
        opacity: 0.8,
        zIndex:-2,
    },
    Title:{
        textAlign: 'center',
        color: 'white',
        fontFamily: 'Audrey-Medium',
        textTransform:'uppercase',
        fontSize: 55,
        marginTop: wp('40%'),
    },
    Subtitle:{
        textAlign: 'center',
        color: 'white',
        fontFamily: 'Audrey-Normal',
        fontSize: 28,
    },
    Scrollable:{
        position:'absolute',
        width: wp('100%'),
        height: hp('100%'),
        // backgroundColor:'red',
        flex:1,
    },
    VerticalContainer:{
        flex:1,
        flexDirection: 'column',
        justifyContent:'space-between',
        marginTop:hp('55%'),
    },
    horizontalScrollable:{
        maxHeight:hp('35%'),
        // marginTop:'25%',
        zIndex:3,
        // backgroundColor:'yellow',
        position:'relative',
        
    },
    panel:{
        // position:'relative',
        width: '100%',
        minHeight: hp('100%'),
        marginTop:'45%',
        backgroundColor: 'white',
        overflow:'hidden',
        // padding: 10,
        flex:1,
        // justifyContent:'center',
        // alignContent:'center',
        // alignItems:'center',
    },
    boxContainerHorizontal:{
        // height:hp('60%'),
        width:wp('100%'),
        maxHeight:'65%',
        flex: 1,
        flexDirection: 'row',
        flexWrap:'wrap',
        // backgroundColor:'yellow',
        justifyContent:'space-around',
        alignContent:'space-around',
        // marginLeft:wp('15%'),
        // marginRight:wp('15%'),
        // position:'relative',
    },
    box1:{
        position:'relative',
        width:wp('46%'),
        height:hp('24%'),
        backgroundColor:'#B0D0D3',
        borderRadius: 40,
        // marginTop:0,
        // marginHorizontal:20,
        shadowOffset:{width: 0, height: 0},
        elevation: 10,
        shadowColor: 'black',
        shadowRadius:2,
        shadowOpacity:1,
    },
    box2:{
        position:'relative',
        width:wp('46%'),
        height:hp('24%'),
        backgroundColor:'#C08497',
        borderRadius: 40,
        // marginTop:7,
        // marginHorizontal:20,
        shadowOffset:{width: 0, height: 0},
        elevation: 10,
        shadowColor: 'black',
        shadowRadius:2,
        shadowOpacity:1,
    },
    box3:{
        position:'relative',
        width:wp('46%'),
        height:hp('24%'),
        backgroundColor:'#F7AF9D',
        borderRadius: 40,
        // marginTop:7,
        // marginHorizontal:20,
        shadowOffset:{width: 0, height: 0},
        elevation: 10,
        shadowColor: 'black',
        shadowRadius:2,
        shadowOpacity:1,
    },
    box4:{
        position:'relative',
        width:wp('46%'),
        height:hp('24%'),
        backgroundColor:'#F7E3AF',
        borderRadius: 40,
        // marginTop:7,
        // marginHorizontal:20,
        shadowOffset:{width: 0, height: 0},
        elevation: 10,
        shadowColor: 'black',
        shadowRadius:2,
        shadowOpacity:1,
    },
    boxTitle:{
        color:'black',
        fontSize:20,
    },
    boxImage:{
        height: '100%',
        width: '100%',
        resizeMode:'stretch',
        borderRadius: 35,
       position:'relative',
       opacity: 0.7
    },
    boxText:{
        fontFamily:"Audrey-Bold",
        marginTop:13,
        // letterSpacing: 4,
        fontSize: 20,
        width:'100%',
        height:'100%',
        color:'white',
        // textAlign: 'center',
        position:'absolute',
        // justifyContent:'center',
        // alignContent:'center',
        // alignItems:'center',
        // marginTop:10,
        // textAlignVertical: 'center',
        padding: 20,
    },
    panelTitle:{
        width:'100%',
        fontSize:30,
        fontFamily:"Audrey-Bold",
        padding:10
    },
    iconContainer:{
        
        position:'absolute',
        backgroundColor:'yellow'
    }
    
})