import React, { StyleSheet } from 'react-native'
import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';

export default StyleSheet.create({
    container:{
        backgroundColor:'white',
        flex: 1,
        height:hp('100%'),
        // marginTop:'-10%'
    },
    itemContainer:{
      width:wp('90%'),
      // height:hp('20%'),
      alignSelf:'center',
      flex: 1,
      flexDirection: 'row',
      flexWrap:'wrap',
      borderRadius:20,
      marginVertical:10,
      backgroundColor:'white',
      padding:20,
      shadowOffset:{width: 0, height: 0},
      elevation: 5,
      shadowColor: 'black',
      shadowRadius:2,
      shadowOpacity:1,
    },
    circle:{
      position:'relative',
      alignSelf:'center',
        // marginLeft:'-30%',
        // marginTop:'-40%',
        height:hp('10%'),
        width:hp('10%'),
        backgroundColor:'white',
        // opacity:0.3,
        borderWidth:4,
        borderRadius:hp('10%')/2,
        zIndex:-1,
        flex:1,
        flexDirection:'column',
      
    },
    userIcon:{
      alignSelf:'center',
      marginTop:'auto',
      marginBottom:'auto',
    },
    userName:{
      position:'relative',
      fontFamily:'Montserrat-SemiBold',
      fontSize:17,
      alignSelf:'center',
      marginTop:hp('1%'),
      // backgroundColor:'yellow'
    },
    carouselContainer:{
        marginTop:hp('2%'),
        // position:'relative',
        flex: 1,
        height:hp('40%'),
        // borderRadius:30,
        // backgroundColor:'yellow',
    },
    carousel: {
        flex: 1,
        position:'relative',
        // borderRadius:50,
      },
      item: {
        width:'100%',
        height:'100%',
        // borderWidth: 2,
        backgroundColor: 'transparent',
        flex: 1,
        // borderRadius: 50,
        // borderColor: 'white',
        flexDirection:'column',
        // justifyContent:'center',
        // alignContent:'center',
        // alignItems:'center',
        // elevation: 3
      },
      title:{
          position:'relative',
          fontSize:23,
          fontFamily:'Montserrat-Bold',
          // backgroundColor:'yellow',
        //   marginRight:'auto',
          marginLeft:'5%',
          color:'black',
        //   textAlign:'center',
          padding:5,
          zIndex:2,
      },
      info:{
        fontFamily:'Montserrat-Medium',
        position:'relative',
        marginLeft:'5%',
        color:"#888888",
      },
      line:{
        borderBottomWidth:0.5,
        borderBottomColor:'#a8a8a8',
        width:'90%',
        alignSelf:'center',
      },
      address:{
        fontFamily:'Montserrat-Medium',
        position:'relative',
        marginTop:-40,
        marginLeft: 25,
      },
      addressList:{
        fontFamily:'Montserrat-Medium',
        position:'relative',
        marginLeft: '5%',
        marginTop:'3%',
      },
      rate:{
        fontFamily:'Montserrat-Medium',
        position:'relative',
        marginTop:-40,
        marginLeft: '87%',
      },
      containerImage:{
        flex:1,
        borderRadius:20,
        backgroundColor:'black',
      },
      iconContainer:{
        marginTop:-12,
        // backgroundColor:'yellow',
        height:'auto',
        marginLeft:15,
        marginRight:'auto',
      },
      iconStarContainer:{
        width:'100%',
        height:'30%',
        position:'absolute',
        // backgroundColor:'yellow',
        marginRight:'auto',
      },
      star:{
        marginLeft:'80%',
        marginTop:'-2%',
        position:'relative',
      },
      plus:{
        alignSelf:'center',
      },
      Image:{
          width:'100%',
          height:'100%',
        //   flex: 1,
          resizeMode:'cover',
          backgroundColor:'black',
        //   borderRadius:30,
      },
      addReview:{
        height:hp('6%'),
        width:hp('6%'),
        backgroundColor:'#DA4167',
        position:'absolute',
        marginTop:hp('2%'),
        marginLeft:wp('74%'),
        borderRadius:10,
        flex:1,
        flexDirection:'column',
        justifyContent:'center'
      },
      closeModal:{
        borderWidth:2,
        borderColor:'#DA4167',
        backgroundColor:'white',
        maxWidth:'30%',
        height:'100%',
        padding:0,
        borderRadius:10,
        flex:1,
        flexDirection:'column',
        justifyContent:'center',
        alignItems:'center',
        marginHorizontal:10 
      },
      infoResto:{
          flex:1,
          flexDirection:'column',
          height:hp('14%'),
          width:'94%',
          backgroundColor:'white',
          position:'absolute',
          borderRadius:20,
        //   justifyContent:'center',
          // alignItems:'center',
          marginTop:hp('24.5%'),
          // marginLeft:0,
          // marginRight:'auto',
          alignSelf:'center',
          padding:4,
      },
      submit:{
        
        backgroundColor:'#DA4167',
        maxWidth:'30%',
        height:'100%',
        padding:0,
        borderRadius:10,
        flex:1,
        flexDirection:'column',
        justifyContent:'center',
        alignItems:'center',
        marginHorizontal:10

      },
})